---
swagger: "2.0"
info:
  description: "Openmoney API"
  version: "2.0.0"
  title: "Openmoney API"
  termsOfService: "http://openmoney.cc/index.php?page=terms"
  contact:
    name: "Openmoney Development Team"
    url: "http://openmoney.cc"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0"
host: "deefactorial.proudleo.com"
basePath: "/V2"
schemes:
- "https"
paths:
  /access_token:
    post:
      tags:
      - "auth"
      description: "Get an access token"
      operationId: "accessTokenPost"
      x-swagger-router-controller: "Auth"
  /authorize:
    post:
      tags:
      - "auth"
      description: "authroize a user"
      operationId: "authorizePost"
      x-swagger-router-controller: "Auth"
  /discovery/accounts:
    get:
      tags:
      - "accounts"
      description: "Discover other users accounts by naming them, this is how you\
        \ add accounts to make payments to."
      operationId: "discoveryAccountsGet"
      security:
      - openmoneyApplication:
        - "read:users"
        - "read:accounts"
      - openmoneyImplicit:
        - "read:users"
        - "read:accounts"
      - internalApiKey: []
      x-swagger-router-controller: "Accounts"
  /discovery/currencies:
    get:
      tags:
      - "currencies"
      description: "Discover other users currencies"
      operationId: "discoveryCurrenciesGet"
      security:
      - openmoneyApplication:
        - "read:users"
        - "read:currencies"
      - openmoneyImplicit:
        - "read:users"
        - "read:currencies"
      - internalApiKey: []
      x-swagger-router-controller: "Currencies"
  /discovery/spaces:
    get:
      tags:
      - "spaces"
      description: "Discover another users space"
      operationId: "discoverySpacesGet"
      security:
      - openmoneyApplication:
        - "read:users"
        - "read:spaces"
      - openmoneyImplicit:
        - "read:users"
        - "read:spaces"
      - internalApiKey: []
      x-swagger-router-controller: "Spaces"
  /oauth/access_token:
    post:
      tags:
      - "auth"
      summary: "Gets an authorization token"
      description: "Gets an authorization token"
      operationId: "oauthAccessTokenPost"
      x-swagger-router-controller: "Auth"
  /oauth/application:
    post:
      tags:
      - "auth"
      description: "Existing user Registers an application with the openmoney network."
      operationId: "oauthApplicationPost"
      security:
      - openmoneyImplicit:
        - "read:users"
        - "write:users"
      - internalApiKey: []
      x-swagger-router-controller: "Auth"
  /oauth/authorize:
    get:
      tags:
      - "auth"
      summary: "Authroize"
      description: "Authorizes a user on the openmoney network"
      operationId: "oauthAuthorizeGet"
      x-swagger-router-controller: "Auth"
  /register:
    post:
      tags:
      - "auth"
      description: "Register a user on the system"
      operationId: "registerPost"
      x-swagger-router-controller: "Auth"
    options:
      tags:
      - "auth"
      operationId: "registerOptions"
      x-swagger-router-controller: "Auth"
  /sync/accounts:
    get:
      tags:
      - "accounts"
      description: "List accounts"
      operationId: "syncAccountsGet"
      security:
      - openmoneyApplication:
        - "read:accounts"
      - openmoneyImplicit:
        - "read:accounts"
      - internalApiKey: []
      x-swagger-router-controller: "Accounts"
    post:
      tags:
      - "accounts"
      description: "create an account"
      operationId: "syncAccountsPost"
      security:
      - openmoneyApplication:
        - "write:accounts"
      - openmoneyImplicit:
        - "write:accounts"
      - internalApiKey: []
      x-swagger-router-controller: "Accounts"
  /sync/accounts/{id}:
    get:
      tags:
      - "accounts"
      description: "Get an account by id"
      operationId: "syncAccountsIdGet"
      security:
      - openmoneyApplication:
        - "read:accounts"
      - openmoneyImplicit:
        - "read:accounts"
      - internalApiKey: []
      x-swagger-router-controller: "Accounts"
    put:
      tags:
      - "accounts"
      description: "Update account"
      operationId: "syncAccountsIdPut"
      security:
      - openmoneyApplication:
        - "write:accounts"
      - openmoneyImplicit:
        - "write:accounts"
      - internalApiKey: []
      x-swagger-router-controller: "Accounts"
    delete:
      tags:
      - "accounts"
      description: "Delete a account"
      operationId: "syncAccountsDelete"
      security:
      - openmoneyApplication:
        - "write:accounts"
      - openmoneyImplicit:
        - "write:accounts"
      - internalApiKey: []
      x-swagger-router-controller: "Accounts"
  /sync/currencies:
    get:
      tags:
      - "currencies"
      description: "List currencies, filter by currency or currency_space"
      operationId: "syncCurrenciesGet"
      security:
      - openmoneyApplication:
        - "read:currencies"
      - openmoneyImplicit:
        - "read:currencies"
      - internalApiKey: []
      x-swagger-router-controller: "Currencies"
    post:
      tags:
      - "currencies"
      description: "Create a currency"
      operationId: "syncCurrenciesPost"
      security:
      - openmoneyApplication:
        - "write:currencies"
      - openmoneyImplicit:
        - "write:currencies"
      - internalApiKey: []
      x-swagger-router-controller: "Currencies"
  /sync/currencies/{id}:
    get:
      tags:
      - "currencies"
      description: "Get a currency by id"
      operationId: "syncCurrenciesIdGet"
      security:
      - openmoneyApplication:
        - "read:currencies"
      - openmoneyImplicit:
        - "read:currencies"
      - internalApiKey: []
      x-swagger-router-controller: "Currencies"
    put:
      tags:
      - "currencies"
      description: "Update Currency"
      operationId: "syncCurrenciesIdPut"
      security:
      - openmoneyApplication:
        - "write:currencies"
      - openmoneyImplicit:
        - "write:currencies"
      - internalApiKey: []
      x-swagger-router-controller: "Currencies"
    delete:
      tags:
      - "currencies"
      description: "Delete a currency"
      security:
      - openmoneyApplication:
        - "write:currencies"
      - openmoneyImplicit:
        - "write:currencies"
      - internalApiKey: []
  /sync/journals:
    get:
      tags:
      - "journals"
      description: "List Journal Entries"
      operationId: "syncJournalsGet"
      security:
      - openmoneyApplication:
        - "read:journals"
      - openmoneyImplicit:
        - "read:journals"
      - internalApiKey: []
      x-swagger-router-controller: "Journals"
    post:
      tags:
      - "journals"
      description: "Create a journal entry"
      operationId: "syncJournalsPost"
      security:
      - openmoneyApplication:
        - "write:journals"
      - openmoneyImplicit:
        - "write:journals"
      - internalApiKey: []
      x-swagger-router-controller: "Journals"
  /sync/journals/{id}:
    get:
      tags:
      - "journals"
      description: "Get Journal by id"
      operationId: "syncJournalsIdGet"
      security:
      - openmoneyApplication:
        - "write:journals"
      - openmoneyImplicit:
        - "write:journals"
      - internalApiKey: []
      x-swagger-router-controller: "Journals"
  /sync/spaces:
    get:
      tags:
      - "spaces"
      description: "List of spaces"
      operationId: "syncSpacesGet"
      security:
      - openmoneyApplication:
        - "read:spaces"
      - openmoneyImplicit:
        - "read:spaces"
      - internalApiKey: []
      x-swagger-router-controller: "Spaces"
    post:
      tags:
      - "spaces"
      description: "Create New Spaces"
      operationId: "syncSpacesPost"
      security:
      - openmoneyApplication:
        - "write:spaces"
      - openmoneyImplicit:
        - "write:spaces"
      - internalApiKey: []
      x-swagger-router-controller: "Spaces"
  /sync/spaces/{id}:
    get:
      tags:
      - "spaces"
      description: "Get a space by id"
      operationId: "syncSpacesIdGet"
      security:
      - openmoneyApplication:
        - "read:spaces"
      - openmoneyImplicit:
        - "read:spaces"
      - internalApiKey: []
      x-swagger-router-controller: "Spaces"
    put:
      tags:
      - "spaces"
      description: "Update Space"
      operationId: "syncSpacesIdPut"
      security:
      - openmoneyApplication:
        - "write:spaces"
      - openmoneyImplicit:
        - "write:spaces"
      x-swagger-router-controller: "Spaces"
    delete:
      tags:
      - "spaces"
      description: "Remove a space"
      operationId: "syncSpacesIdDelete"
      security:
      - openmoneyApplication:
        - "write:spaces"
      - openmoneyImplicit:
        - "write:spaces"
      - internalApiKey: []
      x-swagger-router-controller: "Spaces"
securityDefinitions:
  openmoneyImplicit:
    type: "oauth2"
    authorizationUrl: "http://deefactorial.proudleo.com/V2/authroize"
    tokenUrl: "https://deefactorial.proudleo.com/V2/access_token"
    flow: "accessCode"
    scopes:
      read:users: "Read access to users"
      write:users: "Write access to users"
      read:accounts: "Read access to accounts"
      write:accounts: "Write access to accounts"
      read:currencies: "Read access to currencies"
      write:currencies: "Write access to currencies"
      read:spaces: "Read access to spaces"
      write:spaces: "Write access to spaces"
      read:journals: "Read access to journals"
      write:journals: "Write access  to journals"
  internalApiKey:
    type: "apiKey"
    name: "access_token"
    in: "header"
  openmoneyApplication:
    type: "oauth2"
    authorizationUrl: "https://deefactorial.proudleo.com/V2/oauth/authorize"
    tokenUrl: "https://deefactorial.proudleo.com/V2/oauth/access_token"
    flow: "accessCode"
    scopes:
      read:users: "Read access to users"
      write:users: "Write access to users"
      read:accounts: "Read access to accounts"
      write:accounts: "Write access to accounts"
      read:currencies: "Read access to currencies"
      write:currencies: "Write access to currencies"
      read:spaces: "Read access to spaces"
      write:spaces: "Write access to spaces"
      read:journals: "Read access to journals"
      write:journals: "Write access  to journals"