swagger: '2.0'
info:
  version: 2.0.0
  title: Openmoney API
  description: Openmoney API
  termsOfService: 'http://openmoney.cc/index.php?page=terms'
  contact:
    name: Openmoney Development Team
    url: 'http://openmoney.cc'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: cloud.openmoney.cc
basePath: /V2
schemes:
  - https
paths:
  /stewards:
    get:
      x-swagger-router-controller: Stewards
      operationId: stewardsList
      summary: Get a listing of known stewards
      tags:
        - stewards
      security:
        - oauth2PasswordSecurity:
            - 'read:stewards'
        - oauth2ImplicitSecurity:
            - 'read:stewards'
        - oauth2ApplicationSecurity:
            - 'read:stewards'
        - oauth2AccessCodeSecurity:
            - 'read:stewards'
        - apiKeySecurity: []
        - basicAuthenticationSecurity: []
    post:
      x-swagger-router-controller: Stewards
      operationId: stewardsPost
      summary: Register a steward on the system
      tags:
        - stewards
  /stewards/forgot:
    post:
      x-swagger-router-controller: Stewards
      operationId: stewardsForgotPost
      summary: Forgot password or stewardname request
      tags:
        - stewards
  '/stewards/{stewardname}/reset':
    post:
      x-swagger-router-controller: Stewards
      operationId: stewardsResetPost
      summary: Reset password request
      tags:
        - stewards
  '/stewards/{stewardname}/login':
    get:
      x-swagger-router-controller: Auth
      operationId: loginGet
      summary: Login Page for the steward
      tags:
        - auth
    post:
      x-swagger-router-controller: Auth
      operationId: loginPost
      summary: Login steward
      tags:
        - auth
  '/stewards/{stewardname}/logout':
    get:
      x-swagger-router-controller: Auth
      operationId: logoutPost
      summary: Logout steward
      tags:
        - auth
  '/stewards/{stewardname}/account':
    get:
      x-swagger-router-controller: Auth
      operationId: accountGet
      summary: Get Steward account information
      tags:
        - auth
  '/stewards/{stewardname}/oauth/application':
    post:
      x-swagger-router-controller: Auth
      operationId: oauthApplicationPost
      summary: >-
        Create an application for a client_id and client_secret for oauth token
        authorization.
      description: Existing steward Registers an application with the openmoney network.
      tags:
        - auth
      security:
        - basicAuthenticationSecurity: []
  '/stewards/{stewardname}/dialog/authorize':
    get:
      x-swagger-router-controller: Auth
      operationId: oauthDialogeGet
      summary: >-
        Implicit authorization dialog presented to steward to authorize
        client_id to access API resources on their behalf.
      tags:
        - auth
  '/stewards/{stewardname}/dialog/authorize/decision':
    post:
      x-swagger-router-controller: Auth
      operationId: oauthDialogePost
      description: Authorization dialoge decision with allowed scopes.
      summary: Authorizes a steward on the openmoney network
      tags:
        - auth
  '/stewards/{stewardname}/oauth/token':
    post:
      x-swagger-router-controller: Auth
      operationId: oauthAccessTokenPost
      tags:
        - auth
      summary: >-
        Exchanges the user or client credentials for an access token used to
        access resources.
      security:
        - basicAuthenticationSecurity: []
        - oauth2Refresh: []
  '/stewards/{stewardname}':
    get:
      x-swagger-router-controller: Stewards
      operationId: stewardsGet
      summary: Get a single steward
      tags:
        - stewards
      security:
        - oauth2PasswordSecurity:
            - 'read:stewards'
        - oauth2ImplicitSecurity:
            - 'read:stewards'
        - oauth2ApplicationSecurity:
            - 'read:stewards'
        - oauth2AccessCodeSecurity:
            - 'read:stewards'
        - apiKeySecurity: []
        - basicAuthenticationSecurity: []
    put:
      x-swagger-router-controller: Stewards
      operationId: stewardsPut
      summary: Update a steward account
      tags:
        - stewards
      security:
        - oauth2PasswordSecurity:
            - 'write:stewards'
        - oauth2ImplicitSecurity:
            - 'write:stewards'
        - oauth2ApplicationSecurity:
            - 'write:stewards'
        - oauth2AccessCodeSecurity:
            - 'write:stewards'
        - apiKeySecurity: []
        - basicAuthenticationSecurity: []
    delete:
      x-swagger-router-controller: Stewards
      operationId: stewardsDelete
      summary: Delete a steward account
      tags:
        - stewards
      security:
        - oauth2PasswordSecurity:
            - 'write:stewards'
        - oauth2ImplicitSecurity:
            - 'write:stewards'
        - oauth2ApplicationSecurity:
            - 'write:stewards'
        - oauth2AccessCodeSecurity:
            - 'write:stewards'
        - apiKeySecurity: []
        - basicAuthenticationSecurity: []
  '/stewards/{stewardname}/namespaces':
    get:
      x-swagger-router-controller: Spaces
      operationId: spacesList
      summary: Get a Listing of namespaces known by steward.
      tags:
        - namespaces
      security:
        - oauth2PasswordSecurity:
            - 'read:namespaces'
        - oauth2ImplicitSecurity:
            - 'read:namespaces'
        - oauth2ApplicationSecurity:
            - 'read:namespaces'
        - oauth2AccessCodeSecurity:
            - 'read:namespaces'
        - apiKeySecurity: []
        - basicAuthenticationSecurity: []
    post:
      x-swagger-router-controller: Spaces
      operationId: spacesPost
      summary: Create a namespace
      tags:
        - namespaces
      security:
        - oauth2PasswordSecurity:
            - 'write:namespaces'
        - oauth2ImplicitSecurity:
            - 'write:namespaces'
        - oauth2ApplicationSecurity:
            - 'write:namespaces'
        - oauth2AccessCodeSecurity:
            - 'write:namespaces'
        - apiKeySecurity: []
        - basicAuthenticationSecurity: []
  '/stewards/{stewardname}/namespaces/{namespace}':
    get:
      x-swagger-router-controller: Spaces
      operationId: spacesGet
      summary: Get a namespace by it's name
      tags:
        - namespaces
      security:
        - oauth2PasswordSecurity:
            - 'read:namespaces'
        - oauth2ImplicitSecurity:
            - 'read:namespaces'
        - oauth2ApplicationSecurity:
            - 'read:namespaces'
        - oauth2AccessCodeSecurity:
            - 'read:namespaces'
        - apiKeySecurity: []
        - basicAuthenticationSecurity: []
    put:
      x-swagger-router-controller: Spaces
      operationId: spacesPut
      summary: Update a namespace
      tags:
        - namespaces
      security:
        - oauth2PasswordSecurity:
            - 'write:namespaces'
        - oauth2ImplicitSecurity:
            - 'write:namespaces'
        - oauth2ApplicationSecurity:
            - 'write:namespaces'
        - oauth2AccessCodeSecurity:
            - 'write:namespaces'
        - apiKeySecurity: []
        - basicAuthenticationSecurity: []
    delete:
      x-swagger-router-controller: Spaces
      operationId: spacesDelete
      description: Delete a namespace
      tags:
        - namespaces
      security:
        - oauth2PasswordSecurity:
            - 'write:namespaces'
        - oauth2ImplicitSecurity:
            - 'write:namespaces'
        - oauth2ApplicationSecurity:
            - 'write:namespaces'
        - oauth2AccessCodeSecurity:
            - 'write:namespaces'
        - apiKeySecurity: []
        - basicAuthenticationSecurity: []
  '/stewards/{stewardname}/currencies':
    get:
      x-swagger-router-controller: Currencies
      operationId: currenciesList
      summary: Get a Listing currencies known by steward.
      tags:
        - currencies
      security:
        - oauth2PasswordSecurity:
            - 'read:currencies'
        - oauth2ImplicitSecurity:
            - 'read:currencies'
        - oauth2ApplicationSecurity:
            - 'read:currencies'
        - oauth2AccessCodeSecurity:
            - 'read:currencies'
        - apiKeySecurity: []
        - basicAuthenticationSecurity: []
    post:
      x-swagger-router-controller: Currencies
      operationId: currenciesPost
      summary: Create a currency
      tags:
        - currencies
      security:
        - oauth2PasswordSecurity:
            - 'write:currencies'
        - oauth2ImplicitSecurity:
            - 'write:currencies'
        - oauth2ApplicationSecurity:
            - 'write:currencies'
        - oauth2AccessCodeSecurity:
            - 'write:currencies'
        - apiKeySecurity: []
        - basicAuthenticationSecurity: []
  '/stewards/{stewardname}/currencies/{currency}':
    get:
      x-swagger-router-controller: Currencies
      operationId: currenciesGet
      summary: Get a currency by its name
      tags:
        - currencies
      security:
        - oauth2PasswordSecurity:
            - 'read:currencies'
        - oauth2ImplicitSecurity:
            - 'read:currencies'
        - oauth2ApplicationSecurity:
            - 'read:currencies'
        - oauth2AccessCodeSecurity:
            - 'read:currencies'
        - apiKeySecurity: []
        - basicAuthenticationSecurity: []
    put:
      x-swagger-router-controller: Currencies
      operationId: currenciesPut
      summary: Update a Currency
      tags:
        - currencies
      security:
        - oauth2PasswordSecurity:
            - 'write:currencies'
        - oauth2ImplicitSecurity:
            - 'write:currencies'
        - oauth2ApplicationSecurity:
            - 'write:currencies'
        - oauth2AccessCodeSecurity:
            - 'write:currencies'
        - apiKeySecurity: []
        - basicAuthenticationSecurity: []
    delete:
      x-swagger-router-controller: Currencies
      operationId: currenciesDelete
      summary: Delete a currency
      tags:
        - currencies
      security:
        - oauth2PasswordSecurity:
            - 'write:currencies'
        - oauth2ImplicitSecurity:
            - 'write:currencies'
        - oauth2ApplicationSecurity:
            - 'write:currencies'
        - oauth2AccessCodeSecurity:
            - 'write:currencies'
        - apiKeySecurity: []
        - basicAuthenticationSecurity: []
  '/stewards/{stewardname}/accounts':
    get:
      x-swagger-router-controller: Accounts
      operationId: accountsList
      summary: Get a Listing of accounts in a namespace
      tags:
        - accounts
      security:
        - oauth2PasswordSecurity:
            - 'read:accounts'
        - oauth2ImplicitSecurity:
            - 'read:accounts'
        - oauth2ApplicationSecurity:
            - 'read:accounts'
        - oauth2AccessCodeSecurity:
            - 'read:accounts'
        - apiKeySecurity: []
        - basicAuthenticationSecurity: []
  '/stewards/{stewardname}/namespaces/{namespace}/accounts':
    post:
      x-swagger-router-controller: Accounts
      operationId: accountsPost
      summary: create an account in a namespace
      tags:
        - accounts
      security:
        - oauth2PasswordSecurity:
            - 'write:accounts'
        - oauth2ImplicitSecurity:
            - 'write:accounts'
        - oauth2ApplicationSecurity:
            - 'write:accounts'
        - oauth2AccessCodeSecurity:
            - 'write:accounts'
        - apiKeySecurity: []
        - basicAuthenticationSecurity: []
  '/stewards/{stewardname}/namespaces/{namespace}/accounts/{account}':
    get:
      x-swagger-router-controller: Accounts
      operationId: accountsGet
      summary: Get an account by account name
      tags:
        - accounts
      security:
        - oauth2PasswordSecurity:
            - 'read:accounts'
        - oauth2ImplicitSecurity:
            - 'read:accounts'
        - oauth2ApplicationSecurity:
            - 'read:accounts'
        - oauth2AccessCodeSecurity:
            - 'read:accounts'
        - apiKeySecurity: []
        - basicAuthenticationSecurity: []
    put:
      x-swagger-router-controller: Accounts
      operationId: accountsPut
      summary: Update an account
      tags:
        - accounts
      security:
        - oauth2PasswordSecurity:
            - 'write:accounts'
        - oauth2ImplicitSecurity:
            - 'write:accounts'
        - oauth2ApplicationSecurity:
            - 'write:accounts'
        - oauth2AccessCodeSecurity:
            - 'write:accounts'
        - apiKeySecurity: []
        - basicAuthenticationSecurity: []
    delete:
      x-swagger-router-controller: Accounts
      operationId: accountsDelete
      summary: Delete an account
      tags:
        - accounts
      security:
        - oauth2PasswordSecurity:
            - 'write:accounts'
        - oauth2ImplicitSecurity:
            - 'write:accounts'
        - oauth2ApplicationSecurity:
            - 'write:accounts'
        - oauth2AccessCodeSecurity:
            - 'write:accounts'
        - apiKeySecurity: []
        - basicAuthenticationSecurity: []
  '/stewards/{stewardname}/accounts/lookup':
    get:
      x-swagger-router-controller: Accounts
      operationId: accountsDiscovery
      summary: Lookup an account by it's public key
      tags:
        - accounts
      security:
        - oauth2PasswordSecurity:
            - 'read:stewards'
            - 'read:accounts'
        - oauth2ImplicitSecurity:
            - 'read:stewards'
            - 'read:accounts'
        - oauth2ApplicationSecurity:
            - 'read:stewards'
            - 'read:accounts'
        - oauth2AccessCodeSecurity:
            - 'read:stewards'
            - 'read:accounts'
        - apiKeySecurity: []
        - basicAuthenticationSecurity: []
  '/stewards/{stewardname}/journals':
    get:
      x-swagger-router-controller: Journals
      operationId: journalsList
      summary: List Journal Entries for this accountname
      tags:
        - journals
      security:
        - oauth2PasswordSecurity:
            - 'read:journals'
        - oauth2ImplicitSecurity:
            - 'read:journals'
        - oauth2ApplicationSecurity:
            - 'read:journals'
        - oauth2AccessCodeSecurity:
            - 'read:journals'
        - apiKeySecurity: []
        - basicAuthenticationSecurity: []
  '/stewards/{stewardname}/namespaces/{namespace}/accounts/{account}/journals/{currency}':
    post:
      x-swagger-router-controller: Journals
      operationId: journalsPost
      summary: Create a journal entry for this account
      tags:
        - journals
      security:
        - oauth2PasswordSecurity:
            - 'write:journals'
        - oauth2ImplicitSecurity:
            - 'write:journals'
        - oauth2ApplicationSecurity:
            - 'write:journals'
        - oauth2AccessCodeSecurity:
            - 'write:journals'
        - apiKeySecurity: []
        - basicAuthenticationSecurity: []
securityDefinitions:
  oauth2PasswordSecurity:
    type: oauth2
    scopes:
      'read:stewards': Read access to stewards
      'write:stewards': Write access to stewards
      'read:accounts': Read access to accounts
      'write:accounts': Write access to accounts
      'read:currencies': Read access to currencies
      'write:currencies': Write access to currencies
      'manage:currencies': Manage currencies
      'read:namespaces': Read access to namespaces
      'write:namespaces': Write access to namespaces
      'manage:namespaces': Manage namespaces
      'read:journals': Read access to journals
      'write:journals': Write access  to journals
    flow: password
    tokenUrl: 'https://cloud.openmoney.cc/V2/stewards/%7Bstewardname%7D/oauth/token'
    x-token-operation-id: oauthAccessTokenPost
  oauth2ImplicitSecurity:
    type: oauth2
    scopes:
      'read:stewards': Read access to stewards
      'write:stewards': Write access to stewards
      'read:accounts': Read access to accounts
      'write:accounts': Write access to accounts
      'read:currencies': Read access to currencies
      'write:currencies': Write access to currencies
      'manage:currencies': Manage currencies
      'read:namespaces': Read access to namespaces
      'write:namespaces': Write access to namespaces
      'manage:namespaces': Manage namespaces
      'read:journals': Read access to journals
      'write:journals': Write access  to journals
    flow: implicit
    authorizationUrl: 'http://cloud.openmoney.cc/V2/stewards/%7Bstewardname%7D/dialog/authorize'
    x-token-operation-id: oauthAccessTokenPost
  oauth2ApplicationSecurity:
    type: oauth2
    scopes:
      'read:stewards': Read access to stewards
      'write:stewards': Write access to stewards
      'read:accounts': Read access to accounts
      'write:accounts': Write access to accounts
      'read:currencies': Read access to currencies
      'write:currencies': Write access to currencies
      'manage:currencies': Manage currencies
      'read:namespaces': Read access to namespaces
      'write:namespaces': Write access to namespaces
      'manage:namespaces': Manage namespaces
      'read:journals': Read access to journals
      'write:journals': Write access  to journals
    flow: application
    tokenUrl: 'https://cloud.openmoney.cc/V2/stewards/%7Bstewardname%7D/oauth/token'
    x-token-operation-id: oauthAccessTokenPost
  oauth2AccessCodeSecurity:
    type: oauth2
    scopes:
      'read:stewards': Read access to stewards
      'write:stewards': Write access to stewards
      'read:accounts': Read access to accounts
      'write:accounts': Write access to accounts
      'read:currencies': Read access to currencies
      'write:currencies': Write access to currencies
      'manage:currencies': Manage currencies
      'read:namespaces': Read access to namespaces
      'write:namespaces': Write access to namespaces
      'manage:namespaces': Manage namespaces
      'read:journals': Read access to journals
      'write:journals': Write access  to journals
    flow: accessCode
    authorizationUrl: 'https://cloud.openmoney.cc/V2/stewards/%7Bstewardname%7D/oauth/token'
    x-authroization-operation-id: oauthDialogeGet
    tokenUrl: 'https://cloud.openmoney.cc/V2/stewards/%7Bstewardname%7D/oauth/token'
    x-token-operation-id: oauthAccessTokenPost
  apiKeySecurity:
    type: apiKey
    in: header
    name: Authorization
  oauth2Refresh:
    type: apiKey
    in: header
    name: Authorization
  basicAuthenticationSecurity:
    type: basic